export type Product = {
  id: string;
  name: string;
  designer: string;
  price: number;
  deposit: number;
  category: string;
  gender: "Nữ" | "Nam" | "Unisex";
  occasion: string[];
  sizes: string[];
  colors: string[];
  available: boolean;
  rating: number;
  image: string;
  images?: string[];
};

type ProductSeed = Omit<Product, "available" | "rating" | "image" | "images"> &
  Partial<Pick<Product, "available" | "rating" | "image" | "images">>;

const createProduct = (product: ProductSeed): Product => {
  const image = product.image ?? `/media/product-${product.id}.png`;

  return {
    available: true,
    rating: 4.8,
    ...product,
    image,
    images: product.images ?? [image],
  };
};

export const products: Product[] = [
  createProduct({
    id: "1",
    name: "Đầm hoa mẫu đơn",
    designer: "DIOR",
    price: 350000,
    deposit: 1500000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["#F6D7DF", "#FFF8F1"],
    rating: 4.9,
    image: "/media/product-peony-dress.webp",
  }),
  createProduct({
    id: "2",
    name: "Áo khoác drop họa tiết",
    designer: "DIOR",
    price: 480000,
    deposit: 2000000,
    category: "Áo khoác",
    gender: "Unisex",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["#c9bea8", "#f4f1ea"],
    rating: 4.8,
    image: "/media/product-drop-jacket.webp",
  }),
  createProduct({
    id: "3",
    name: "Nón bucket beige",
    designer: "DIOR",
    price: 420000,
    deposit: 1800000,
    category: "Phụ kiện",
    gender: "Unisex",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#d8ccb7", "#f4efe7"],
    rating: 5,
    image: "/media/product-bucket-beige.webp",
  }),
  createProduct({
    id: "4",
    name: "Túi Bow hồng",
    designer: "DIOR",
    price: 180000,
    deposit: 800000,
    category: "Phụ kiện",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#f1cbd6"],
    rating: 4.6,
    image: "/media/product-bow-bag-pink.webp",
  }),

  // Sản phẩm mới từ file "FASTWear | Đồ nữ.docx". Ảnh đang dùng placeholder để dễ thay bằng ảnh thật.
  createProduct({
    id: "nu-blazer-hobbs",
    name: "Blazer HOBBS",
    designer: "HOBBS",
    price: 200000,
    deposit: 600000,
    category: "Công sở",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["M"],
    colors: ["#c9a27a"],
  }),
  createProduct({
    id: "nu-blazer-massimo-dutti",
    name: "Blazer Massimo Dutti",
    designer: "Massimo Dutti",
    price: 180000,
    deposit: 600000,
    category: "Công sở",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["M"],
    colors: ["#d7c2a7", "#ffffff"],
  }),
  createProduct({
    id: "nu-so-mi-urban-revivo",
    name: "Sơ mi Urban Revivo",
    designer: "Urban Revivo",
    price: 120000,
    deposit: 500000,
    category: "Áo sơ mi",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M"],
    colors: ["#ffffff"],
  }),
  createProduct({
    id: "nu-vay-midi-nem",
    name: "Váy Midi công sở NEM",
    designer: "NEM",
    price: 180000,
    deposit: 600000,
    category: "Chân váy",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["M"],
    colors: ["#b86f66"],
  }),
  createProduct({
    id: "nu-so-mi-lua-reformation",
    name: "Sơ mi lụa Reformation",
    designer: "Reformation",
    price: 150000,
    deposit: 500000,
    category: "Áo sơ mi",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["M"],
    colors: ["#b86f66"],
  }),
  createProduct({
    id: "nu-dam-sequin-zara",
    name: "Đầm sequin Zara",
    designer: "Zara",
    price: 300000,
    deposit: 800000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Dạ hội", "Chụp ảnh"],
    sizes: ["M"],
    colors: ["#F2C4CE"],
  }),
  createProduct({
    id: "nu-dam-cocktail-do",
    name: "Đầm Cocktail Đỏ",
    designer: "FASTWear",
    price: 250000,
    deposit: 800000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội"],
    sizes: ["Free"],
    colors: ["#6B1A33"],
  }),
  createProduct({
    id: "nu-dam-nude-champagne",
    name: "Đầm dự tiệc màu nude champagne",
    designer: "FASTWear",
    price: 200000,
    deposit: 700000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["S"],
    colors: ["#ead1bd"],
  }),
  createProduct({
    id: "nu-dam-satin-xanh-ngoc",
    name: "Đầm dự tiệc satin xanh ngọc",
    designer: "FASTWear",
    price: 280000,
    deposit: 800000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["S", "M"],
    colors: ["#76c7b7"],
  }),
  createProduct({
    id: "nu-dam-lech-vai-den",
    name: "Đầm dự tiệc lệch vai",
    designer: "FASTWear",
    price: 240000,
    deposit: 900000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["S", "M"],
    colors: ["#1A1A1A"],
  }),
  createProduct({
    id: "nu-da-hoi-trang-xe-ta",
    name: "Dạ hội trắng xẻ tà",
    designer: "FASTWear",
    price: 250000,
    deposit: 800000,
    category: "Đầm Dạ Hội",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["S", "M"],
    colors: ["#ffffff"],
  }),
  createProduct({
    id: "nu-dam-da-hoi-tay-dai",
    name: "Đầm dạ hội tay dài",
    designer: "FASTWear",
    price: 200000,
    deposit: 700000,
    category: "Đầm Dạ Hội",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["S", "M"],
    colors: ["#ffffff"],
  }),
  createProduct({
    id: "nu-suit-cong-so-kem",
    name: "Suit công sở nữ",
    designer: "FASTWear",
    price: 200000,
    deposit: 800000,
    category: "Suit nữ",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M"],
    colors: ["#f4efe7"],
  }),
  createProduct({
    id: "nu-suit-cong-so-nau",
    name: "Suit công sở nữ nâu",
    designer: "FASTWear",
    price: 180000,
    deposit: 700000,
    category: "Suit nữ",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M"],
    colors: ["#8c6a50"],
  }),
  createProduct({
    id: "nu-set-cong-so-burgundy",
    name: "Set công sở nữ",
    designer: "FASTWear",
    price: 210000,
    deposit: 850000,
    category: "Set công sở",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M"],
    colors: ["#6B1A33", "#1A1A1A"],
  }),

  // Sản phẩm mới từ file "FASTWear | Đồ Nam.docx".
  createProduct({
    id: "nam-suit-toi-mau",
    name: "Suit nam tối màu",
    designer: "FASTWear",
    price: 300000,
    deposit: 1500000,
    category: "Suit Nam",
    gender: "Nam",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["M", "L", "XL"],
    colors: ["#2f3438"],
  }),
  createProduct({
    id: "nam-suit-sang-trong",
    name: "Suit nam sang trọng",
    designer: "FASTWear",
    price: 400000,
    deposit: 2000000,
    category: "Suit Nam",
    gender: "Nam",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["M", "L", "XL"],
    colors: ["#c5a67e"],
  }),
  createProduct({
    id: "nam-vest-du-tiec",
    name: "Vest nam dự tiệc",
    designer: "FASTWear",
    price: 500000,
    deposit: 2000000,
    category: "Vest Nam",
    gender: "Nam",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["M", "L", "XL"],
    colors: ["#1A1A1A"],
  }),
  createProduct({
    id: "nam-so-mi-nhieu-mau",
    name: "Áo sơ mi nam nhiều màu",
    designer: "FASTWear",
    price: 120000,
    deposit: 800000,
    category: "Áo sơ mi",
    gender: "Nam",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["M", "L", "XL"],
    colors: ["#ffffff", "#1A1A1A", "#6B1A33"],
  }),
  createProduct({
    id: "nam-quan-tay-nhieu-mau",
    name: "Quần tây nam nhiều màu",
    designer: "FASTWear",
    price: 150000,
    deposit: 500000,
    category: "Quần tây",
    gender: "Nam",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["M", "L", "XL"],
    colors: ["#1A1A1A", "#3a3a3a"],
  }),

  // Sản phẩm mới từ file "FASTWear | Phụ kiện.docx".
  createProduct({
    id: "pk-cao-got-vien-da",
    name: "Cao gót viền đá",
    designer: "FASTWear",
    price: 100000,
    deposit: 800000,
    category: "Giày",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["36", "37", "38"],
    colors: ["#1A1A1A"],
  }),
  createProduct({
    id: "pk-cao-got-dolce-gabbana",
    name: "Cao gót da Dolce & Gabbana",
    designer: "Dolce & Gabbana",
    price: 180000,
    deposit: 1000000,
    category: "Giày",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["37", "39"],
    colors: ["#f4efe7"],
  }),
  createProduct({
    id: "pk-ysl-slingback-trang",
    name: "YSL Slingback trắng",
    designer: "YSL",
    price: 200000,
    deposit: 1500000,
    category: "Giày",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["37"],
    colors: ["#ffffff"],
  }),
  createProduct({
    id: "pk-valentino-garavani",
    name: "Valentino Garavani",
    designer: "Valentino",
    price: 400000,
    deposit: 2000000,
    category: "Giày",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["38"],
    colors: ["#d8ccb7"],
  }),
  createProduct({
    id: "pk-tabby-shoulder-coach",
    name: "Túi xách Tabby Shoulder Coach",
    designer: "Coach",
    price: 400000,
    deposit: 2000000,
    category: "Túi xách",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#1A1A1A", "#ffffff"],
  }),
  createProduct({
    id: "pk-kissblock-pouch-coach",
    name: "Túi xách Kissblock Pouch 20 Coach",
    designer: "Coach",
    price: 400000,
    deposit: 2000000,
    category: "Túi xách",
    gender: "Nữ",
    occasion: ["Dạ hội", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#1A1A1A"],
  }),
  createProduct({
    id: "pk-bucket-monogram-tory-burch",
    name: "Túi Bucket T Monogram Tory Burch",
    designer: "Tory Burch",
    price: 400000,
    deposit: 2000000,
    category: "Túi xách",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#f4efe7"],
  }),
  createProduct({
    id: "pk-trang-suc-bac-swaroski",
    name: "Set trang sức bạc Swaroski",
    designer: "Swaroski",
    price: 500000,
    deposit: 2000000,
    category: "Trang sức",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#d8d8d8"],
  }),
  createProduct({
    id: "pk-trang-suc-ngoc-trai",
    name: "Set trang sức ngọc trai",
    designer: "FASTWear",
    price: 200000,
    deposit: 800000,
    category: "Trang sức",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#fff8f1"],
  }),
  createProduct({
    id: "pk-dong-ho-daniel-wellington",
    name: "Đồng hồ da Daniel Wellington",
    designer: "Daniel Wellington",
    price: 200000,
    deposit: 800000,
    category: "Đồng hồ",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#ffffff", "#c5a059"],
  }),
  createProduct({
    id: "pk-giay-nam-john-lobb",
    name: "Giày nam John Lobb City II",
    designer: "John Lobb",
    price: 500000,
    deposit: 2000000,
    category: "Giày",
    gender: "Nam",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["8"],
    colors: ["#1A1A1A"],
  }),
  createProduct({
    id: "pk-giay-tay-nam-bitis",
    name: "Giày tây nam Biti's",
    designer: "Biti's",
    price: 120000,
    deposit: 500000,
    category: "Giày",
    gender: "Nam",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["M", "L"],
    colors: ["#1A1A1A", "#3a2a1a"],
  }),
  createProduct({
    id: "pk-dong-ho-nam-seiko",
    name: "Đồng hồ nam Seiko",
    designer: "Seiko",
    price: 200000,
    deposit: 800000,
    category: "Đồng hồ",
    gender: "Nam",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["37mm"],
    colors: ["#1A1A1A", "#345b86", "#ffffff"],
  }),
  createProduct({
    id: "pk-kep-caravat",
    name: "Kẹp caravat",
    designer: "FASTWear",
    price: 50000,
    deposit: 50000,
    category: "Phụ kiện nam",
    gender: "Nam",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#d8d8d8", "#c5a059", "#1A1A1A"],
  }),
  createProduct({
    id: "pk-khuy-mang-set-tron",
    name: "Khuy măng sét tròn",
    designer: "FASTWear",
    price: 50000,
    deposit: 50000,
    category: "Phụ kiện nam",
    gender: "Nam",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#d8d8d8", "#c5a059", "#1A1A1A", "#345b86"],
  }),
  createProduct({
    id: "pk-ghim-cai-ao",
    name: "Ghim cài áo",
    designer: "FASTWear",
    price: 50000,
    deposit: 50000,
    category: "Phụ kiện nam",
    gender: "Nam",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#d8d8d8", "#c5a059", "#1A1A1A", "#fff8f1"],
  }),

  // New products imported from Products_Master CSV
  createProduct({
    id: "tui-xach-nau-chautfifth",
    name: "Túi xách Mini Y2K POCKET màu Nâu Choco x Da beo Nâu",
    designer: "Chautfifth",
    price: 139000,
    deposit: 800000,
    category: "Túi xách",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#413132"],
    rating: 4.6,
    image: "/media/tui-xach-nau-chautfifth.png",
  }),
  createProduct({
    id: "tui-xach-xanh-chautfifth",
    name: "Túi xách C5-Pocket màu xanh xi măng",
    designer: "Chautfifth",
    price: 99000,
    deposit: 600000,
    category: "Túi xách",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#495256"],
    rating: 4.7,
    image: "/media/tui-xach-xanh-chautfifth.png",
  }),
  createProduct({
    id: "tui-xach-vang-urban-revivo",
    name: "Túi xách nữ hình bán nguyệt đính hoa",
    designer: "URBAN REVIVO",
    price: 99000,
    deposit: 500000,
    category: "Túi xách",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#f5f0c6"],
    rating: 4.8,
    image: "/media/tui-xach-vang-urban-revivo.png",
  }),
  createProduct({
    id: "tui-xach-ban-nguyet",
    name: "Túi xách hình bán nguyệt Jatte",
    designer: "PEDRO",
    price: 199000,
    deposit: 1600000,
    category: "Túi xách",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#cec6bd"],
    rating: 4.9,
    image: "/media/tui-xach-ban-nguyet.png",
  }),
  createProduct({
    id: "tui-cam-tay-cnk",
    name: "Túi cầm tay Arwen Quilted Top Handle-đen",
    designer: "CHARLES & KEITH",
    price: 169000,
    deposit: 900000,
    category: "Túi xách",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#282828"],
    rating: 4.5,
    image: "/media/tui-cam-tay-cnk.png",
  }),
  createProduct({
    id: "giay-ballet-puma",
    name: "Giày Speedcat Ballet Suede Nữ - Black-Mauve Mist",
    designer: "PUMA",
    price: 149000,
    deposit: 900000,
    category: "Giày",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["36", "39"],
    colors: ["#ffe8f5"],
    rating: 4.7,
    image: "/media/giay-ballet-puma.png",
  }),
  createProduct({
    id: "giay-onitsuka",
    name: "MEXICO 66 SD - Vàng",
    designer: "Onitsuka Tiger",
    price: 249000,
    deposit: 3000000,
    category: "Giày",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["39"],
    colors: ["#e2b33c"],
    rating: 4.9,
    image: "/media/giay-onitsuka.png",
  }),
  createProduct({
    id: "giay-trang-den",
    name: "Giày Bệt Nữ Hở Gót",
    designer: "FASTWear",
    price: 49000,
    deposit: 100000,
    category: "Giày",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Dạo phố"],
    sizes: ["36", "37", "38", "39"],
    colors: ["#f1f0ef"],
    rating: 4.5,
    image: "/media/giay-trang-den.png",
  }),
  createProduct({
    id: "boots-co-cao-nau",
    name: "Boots Cổ Cao - Nâu",
    designer: "FASTWear",
    price: 69000,
    deposit: 120000,
    category: "Giày",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["36", "37", "38", "39"],
    colors: ["#5d4136"],
    rating: 4.5,
    image: "/media/boots-co-cao-nau.png",
  }),
  createProduct({
    id: "dam-midi-xep-ly-matilda",
    name: "Đầm Midi Xếp Ly Matilda",
    designer: "Lane JT",
    price: 300000,
    deposit: 1000000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội"],
    sizes: ["S", "M", "L"],
    colors: ["#A0262A"],
    rating: 4.8,
    image: "/media/dam-midi-xep-ly-matilda.jpeg",
  }),
  createProduct({
    id: "bam-dress",
    name: "Váy Bam",
    designer: "Ononmade",
    price: 300000,
    deposit: 1000000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Dạo phố"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["#DBDFD9"],
    rating: 4.6,
    image: "/media/bam-dress.jpg",
  }),
  createProduct({
    id: "dam-xuan-he-tay-bong-xep-ly-eo-day-no-co",
    name: "Đầm xuân hè tay bồng",
    designer: "JM Dress Design",
    price: 120000,
    deposit: 400000,
    category: "Công sở",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M", "L"],
    colors: ["#E9C3C2"],
    rating: 4.3,
    image: "/media/dam-xuan-he-tay-bong-xep-ly-eo-day-no-co.jpg",
  }),
  createProduct({
    id: "ao-choang-riili",
    name: "Áo choàng Riili",
    designer: "White Ant",
    price: 300000,
    deposit: 1000000,
    category: "Công sở",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#D4D3DA"],
    rating: 4.5,
    image: "/media/ao-choang-riili.webp",
  }),
  createProduct({
    id: "ao-so-mi-vai-ru-co-day-buoc",
    name: "Áo sơ mi vải rũ có dây buộc",
    designer: "Zara",
    price: 100000,
    deposit: 500000,
    category: "Áo sơ mi",
    gender: "Nam",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["#E8E7E5"],
    rating: 4.9,
    image: "/media/ao-so-mi-vai-ru-co-day-buoc.jpg",
  }),
  createProduct({
    id: "ao-dai-tu-ky",
    name: "Áo dài Tử Kỳ",
    designer: "Keira Tong",
    price: 600000,
    deposit: 1500000,
    category: "Đầm Dạ Hội",
    gender: "Nữ",
    occasion: ["Dạ hội", "Chụp ảnh"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["#E4D1F5"],
    rating: 4.5,
    image: "/media/ao-dai-tu-ky.png",
  }),
  createProduct({
    id: "dottie-dress",
    name: "Váy Dottie",
    designer: "JUBIN",
    price: 200000,
    deposit: 900000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["#ECE6DA"],
    rating: 4.2,
    image: "/media/dottie-dress.jpg",
  }),
  createProduct({
    id: "ao-ren-trang-sat-nach-dinh-long-tag-flane-nguc",
    name: "Áo ren đính lông",
    designer: "FLANE",
    price: 100000,
    deposit: 500000,
    category: "Áo sơ mi",
    gender: "Nữ",
    occasion: ["Dạ hội", "Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["#D9D8DC"],
    rating: 4.4,
    image: "/media/ao-ren-trang-sat-nach-dinh-long-tag-flane-nguc.jpg",
  }),
  createProduct({
    id: "chan-vay-lua-midi-duoi-ca",
    name: "Chân váy lụa midi đuôi cá",
    designer: "H.I.U Fashion",
    price: 80000,
    deposit: 300000,
    category: "Chân váy",
    gender: "Nữ",
    occasion: ["Dạ hội", "Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M", "L"],
    colors: ["#F1EEE9"],
    rating: 4.5,
    image: "/media/chan-vay-lua-midi-duoi-ca.jpg",
  }),
  createProduct({
    id: "quan-ong-rong-xep-ly-phoi-hop",
    name: "Quần ống rộng xếp ly phối hợp",
    designer: "DWARFS Viet Nam",
    price: 100000,
    deposit: 500000,
    category: "Quần tây",
    gender: "Nam",
    occasion: ["Dạ hội", "Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["#847A72"],
    rating: 4.1,
    image: "/media/quan-ong-rong-xep-ly-phoi-hop.webp",
  }),
  createProduct({
    id: "quan-dai-ong-barrel-mau-nau",
    name: "Quần dài ống barrel",
    designer: "Uniqlo",
    price: 120000,
    deposit: 500000,
    category: "Quần tây",
    gender: "Nam",
    occasion: ["Dạ hội", "Dạo phố", "Chụp ảnh"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    colors: ["#473527"],
    rating: 4.8,
    image: "/media/quan-dai-ong-barrel-mau-nau.avif",
  }),
  createProduct({
    id: "ao-khoac-denim-adilenium-5.0",
    name: "Áo khoác Denim Adilenium",
    designer: "Adidas",
    price: 300000,
    deposit: 1000000,
    category: "Áo khoác",
    gender: "Nam",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["#CEE1F1"],
    rating: 4.3,
    image: "/media/ao-khoac-denim-adilenium-5.0.avif",
  }),
  createProduct({
    id: "dam-ren-theu-hoa-hong-aitana",
    name: "Đầm ren thêu hoa hồng Aitana",
    designer: "Simple retro",
    price: 300000,
    deposit: 1000000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["#E6D5C6"],
    rating: 4.9,
    image: "/media/dam-ren-theu-hoa-hong-aitana.webp",
  }),
  createProduct({
    id: "ao-vest-khong-tay-xep-vat-phoi-ke",
    name: "Áo vest không tay xếp vạt phối kẻ",
    designer: "Mono Talk",
    price: 120000,
    deposit: 500000,
    category: "Suit Nữ",
    gender: "Nữ",
    occasion: ["Dạ hội", "Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M", "L"],
    colors: ["#1A2129"],
    rating: 4.3,
    image: "/media/ao-vest-khong-tay-xep-vat-phoi-ke.jpg",
  }),
  createProduct({
    id: "roiki-dress",
    name: "Váy Roiki",
    designer: "Goût De Jun",
    price: 80000,
    deposit: 300000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Dạ hội", "Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M"],
    colors: ["#FFFFFF"],
    rating: 4.1,
    image: "/media/roiki-dress.jpg",
  }),

  // New products imported from updated Products_Master CSV
  createProduct({
    id: "dong-ho-carnival-nu",
    name: "Đồng hồ Carnival nữ 8131L2-CH-HK",
    designer: "CARNIVAL",
    price: 199000,
    deposit: 2500000,
    category: "Đồng hồ",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#e4e2e0"],
    rating: 4.8,
    image: "/media/dong-ho-carnival-nu.png",
  }),
  createProduct({
    id: "dong-ho-carnival-nam",
    name: "Đồng hồ Carnival nam 8108G-VH-D",
    designer: "CARNIVAL",
    price: 279000,
    deposit: 3500000,
    category: "Đồng hồ",
    gender: "Nam",
    occasion: ["Tiệc cưới", "Dạ hội", "Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#f4d7b8"],
    rating: 4.8,
    image: "/media/dong-ho-carnival-nam.png",
  }),
  createProduct({
    id: "mu-len-mlb",
    name: "Nón len unisex tai mèo kẻ sọc Summer MLB",
    designer: "MLB",
    price: 99000,
    deposit: 800000,
    category: "Phụ kiện",
    gender: "Unisex",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#aeceeb"],
    rating: 4.9,
    image: "/media/mu-len-mlb.png",
  }),
  createProduct({
    id: "non-xanh-mlb",
    name: "Nón bóng chày unisex Signature Patch Mesh MLB",
    designer: "MLB",
    price: 99000,
    deposit: 800000,
    category: "Phụ kiện",
    gender: "Unisex",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#0a3b87"],
    rating: 4.9,
    image: "/media/non-xanh-mlb.png",
  }),
  createProduct({
    id: "giay-adidas",
    name: "Giày Thể Thao Adidas VL Court Base Nam",
    designer: "adidas",
    price: 139000,
    deposit: 1000000,
    category: "Giày",
    gender: "Unisex",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["40"],
    colors: ["#d5d7db"],
    rating: 4.5,
    image: "/media/giay-adidas.png",
  }),
];

export function calculateRentalPrice(basePrice: number, rentalDays: number) {
  const safeDays = Math.max(1, rentalDays || 1);
  // Day 1: 100% base price. Day 2+: 80% (20% discount).
  const total = basePrice + Math.max(0, safeDays - 1) * basePrice * 0.8;
  return Math.round(total);
}

export type RentalBreakdownItem = {
  day: number;
  price: number;
  label: string;
  date?: string;
};

export function getRentalBreakdown(
  basePrice: number,
  rentalDays: number,
  startDate?: string | Date,
): RentalBreakdownItem[] {
  const safeDays = Math.max(1, rentalDays || 1);
  const start = startDate ? new Date(startDate) : null;
  const items: RentalBreakdownItem[] = [];
  for (let i = 0; i < safeDays; i++) {
    const isFirst = i === 0;
    const price = isFirst ? basePrice : basePrice * 0.8;
    let date: string | undefined;
    if (start && !Number.isNaN(start.getTime())) {
      const d = new Date(start);
      d.setDate(start.getDate() + i);
      date = d.toLocaleDateString("vi-VN");
    }
    items.push({
      day: i + 1,
      price: Math.round(price),
      label: isFirst ? `Ngày ${i + 1} (giá gốc)` : `Ngày ${i + 1} (−20%)`,
      date,
    });
  }
  return items;
}

export function calculateRentalDeposit(basePrice: number) {
  return Math.round(basePrice * 0.5);
}

export const formatVND = (n: number) => new Intl.NumberFormat("vi-VN").format(n) + "₫";

