export type Product = {
  id: string;
  name: string;
  designer: string;
  price: number;
  deposit: number;
  category: string;
  gender: "Nữ" | "Nam" | "Unisex";
  occasion: string[];
  sizes: string[];
  colors: string[];
  available: boolean;
  rating: number;
  image: string;
  images?: string[];
};

type ProductSeed = Omit<Product, "available" | "rating" | "image" | "images"> &
  Partial<Pick<Product, "available" | "rating" | "image" | "images">>;

const createProduct = (product: ProductSeed): Product => {
  const image = product.image ?? `/media/product-${product.id}.png`;

  return {
    available: true,
    rating: 4.8,
    ...product,
    image,
    images: product.images ?? [image],
  };
};

export const products: Product[] = [
  createProduct({
    id: "1",
    name: "Đầm hoa mẫu đơn",
    designer: "DIOR",
    price: 350000,
    deposit: 1500000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["#F6D7DF", "#FFF8F1"],
    rating: 4.9,
    image: "/media/product-peony-dress.webp",
  }),
  createProduct({
    id: "2",
    name: "Áo khoác drop họa tiết",
    designer: "DIOR",
    price: 480000,
    deposit: 2000000,
    category: "Áo khoác",
    gender: "Unisex",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["#c9bea8", "#f4f1ea"],
    rating: 4.8,
    image: "/media/product-drop-jacket.webp",
  }),
  createProduct({
    id: "3",
    name: "Nón bucket beige",
    designer: "DIOR",
    price: 420000,
    deposit: 1800000,
    category: "Phụ kiện",
    gender: "Unisex",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#d8ccb7", "#f4efe7"],
    rating: 5,
    image: "/media/product-bucket-beige.webp",
  }),
  createProduct({
    id: "4",
    name: "Túi Bow hồng",
    designer: "DIOR",
    price: 180000,
    deposit: 800000,
    category: "Phụ kiện",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#f1cbd6"],
    rating: 4.6,
    image: "/media/product-bow-bag-pink.webp",
  }),

  // Sản phẩm mới từ file "FASTWear | Đồ nữ.docx". Ảnh đang dùng placeholder để dễ thay bằng ảnh thật.
  createProduct({
    id: "nu-blazer-hobbs",
    name: "Blazer HOBBS",
    designer: "HOBBS",
    price: 200000,
    deposit: 600000,
    category: "Công sở",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["M"],
    colors: ["#c9a27a"],
  }),
  createProduct({
    id: "nu-blazer-massimo-dutti",
    name: "Blazer Massimo Dutti",
    designer: "Massimo Dutti",
    price: 180000,
    deposit: 600000,
    category: "Công sở",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["M"],
    colors: ["#d7c2a7", "#ffffff"],
  }),
  createProduct({
    id: "nu-so-mi-urban-revivo",
    name: "Sơ mi Urban Revivo",
    designer: "Urban Revivo",
    price: 120000,
    deposit: 500000,
    category: "Áo sơ mi",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M"],
    colors: ["#ffffff"],
  }),
  createProduct({
    id: "nu-vay-midi-nem",
    name: "Váy Midi công sở NEM",
    designer: "NEM",
    price: 180000,
    deposit: 600000,
    category: "Chân váy",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["M"],
    colors: ["#b86f66"],
  }),
  createProduct({
    id: "nu-so-mi-lua-reformation",
    name: "Sơ mi lụa Reformation",
    designer: "Reformation",
    price: 150000,
    deposit: 500000,
    category: "Áo sơ mi",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["M"],
    colors: ["#b86f66"],
  }),
  createProduct({
    id: "nu-dam-sequin-zara",
    name: "Đầm sequin Zara",
    designer: "Zara",
    price: 300000,
    deposit: 800000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Dạ hội", "Chụp ảnh"],
    sizes: ["M"],
    colors: ["#F2C4CE"],
  }),
  createProduct({
    id: "nu-dam-cocktail-do",
    name: "Đầm Cocktail Đỏ",
    designer: "FASTWear",
    price: 250000,
    deposit: 800000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội"],
    sizes: ["Free"],
    colors: ["#6B1A33"],
  }),
  createProduct({
    id: "nu-dam-nude-champagne",
    name: "Đầm dự tiệc màu nude champagne",
    designer: "FASTWear",
    price: 200000,
    deposit: 700000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["S"],
    colors: ["#ead1bd"],
  }),
  createProduct({
    id: "nu-dam-satin-xanh-ngoc",
    name: "Đầm dự tiệc satin xanh ngọc",
    designer: "FASTWear",
    price: 280000,
    deposit: 800000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["S", "M"],
    colors: ["#76c7b7"],
  }),
  createProduct({
    id: "nu-dam-lech-vai-den",
    name: "Đầm dự tiệc lệch vai",
    designer: "FASTWear",
    price: 240000,
    deposit: 900000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["S", "M"],
    colors: ["#1A1A1A"],
  }),
  createProduct({
    id: "nu-da-hoi-trang-xe-ta",
    name: "Dạ hội trắng xẻ tà",
    designer: "FASTWear",
    price: 250000,
    deposit: 800000,
    category: "Đầm Dạ Hội",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["S", "M"],
    colors: ["#ffffff"],
  }),
  createProduct({
    id: "nu-dam-da-hoi-tay-dai",
    name: "Đầm dạ hội tay dài",
    designer: "FASTWear",
    price: 200000,
    deposit: 700000,
    category: "Đầm Dạ Hội",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["S", "M"],
    colors: ["#ffffff"],
  }),
  createProduct({
    id: "nu-suit-cong-so-kem",
    name: "Suit công sở nữ",
    designer: "FASTWear",
    price: 200000,
    deposit: 800000,
    category: "Suit nữ",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M"],
    colors: ["#f4efe7"],
  }),
  createProduct({
    id: "nu-suit-cong-so-nau",
    name: "Suit công sở nữ nâu",
    designer: "FASTWear",
    price: 180000,
    deposit: 700000,
    category: "Suit nữ",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M"],
    colors: ["#8c6a50"],
  }),
  createProduct({
    id: "nu-set-cong-so-burgundy",
    name: "Set công sở nữ",
    designer: "FASTWear",
    price: 210000,
    deposit: 850000,
    category: "Set công sở",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["S", "M"],
    colors: ["#6B1A33", "#1A1A1A"],
  }),

  // Sản phẩm mới từ file "FASTWear | Đồ Nam.docx".
  createProduct({
    id: "nam-suit-toi-mau",
    name: "Suit nam tối màu",
    designer: "FASTWear",
    price: 300000,
    deposit: 1500000,
    category: "Suit Nam",
    gender: "Nam",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["M", "L", "XL"],
    colors: ["#2f3438"],
  }),
  createProduct({
    id: "nam-suit-sang-trong",
    name: "Suit nam sang trọng",
    designer: "FASTWear",
    price: 400000,
    deposit: 2000000,
    category: "Suit Nam",
    gender: "Nam",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["M", "L", "XL"],
    colors: ["#c5a67e"],
  }),
  createProduct({
    id: "nam-vest-du-tiec",
    name: "Vest nam dự tiệc",
    designer: "FASTWear",
    price: 500000,
    deposit: 2000000,
    category: "Vest Nam",
    gender: "Nam",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["M", "L", "XL"],
    colors: ["#1A1A1A"],
  }),
  createProduct({
    id: "nam-so-mi-nhieu-mau",
    name: "Áo sơ mi nam nhiều màu",
    designer: "FASTWear",
    price: 120000,
    deposit: 800000,
    category: "Áo sơ mi",
    gender: "Nam",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["M", "L", "XL"],
    colors: ["#ffffff", "#1A1A1A", "#6B1A33"],
  }),
  createProduct({
    id: "nam-quan-tay-nhieu-mau",
    name: "Quần tây nam nhiều màu",
    designer: "FASTWear",
    price: 150000,
    deposit: 500000,
    category: "Quần tây",
    gender: "Nam",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["M", "L", "XL"],
    colors: ["#1A1A1A", "#3a3a3a"],
  }),

  // Sản phẩm mới từ file "FASTWear | Phụ kiện.docx".
  createProduct({
    id: "pk-cao-got-vien-da",
    name: "Cao gót viền đá",
    designer: "FASTWear",
    price: 100000,
    deposit: 800000,
    category: "Giày",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["36", "37", "38"],
    colors: ["#1A1A1A"],
  }),
  createProduct({
    id: "pk-cao-got-dolce-gabbana",
    name: "Cao gót da Dolce & Gabbana",
    designer: "Dolce & Gabbana",
    price: 180000,
    deposit: 1000000,
    category: "Giày",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["37", "39"],
    colors: ["#f4efe7"],
  }),
  createProduct({
    id: "pk-ysl-slingback-trang",
    name: "YSL Slingback trắng",
    designer: "YSL",
    price: 200000,
    deposit: 1500000,
    category: "Giày",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["37"],
    colors: ["#ffffff"],
  }),
  createProduct({
    id: "pk-valentino-garavani",
    name: "Valentino Garavani",
    designer: "Valentino",
    price: 400000,
    deposit: 2000000,
    category: "Giày",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["38"],
    colors: ["#d8ccb7"],
  }),
  createProduct({
    id: "pk-tabby-shoulder-coach",
    name: "Túi xách Tabby Shoulder Coach",
    designer: "Coach",
    price: 400000,
    deposit: 2000000,
    category: "Túi xách",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#1A1A1A", "#ffffff"],
  }),
  createProduct({
    id: "pk-kissblock-pouch-coach",
    name: "Túi xách Kissblock Pouch 20 Coach",
    designer: "Coach",
    price: 400000,
    deposit: 2000000,
    category: "Túi xách",
    gender: "Nữ",
    occasion: ["Dạ hội", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#1A1A1A"],
  }),
  createProduct({
    id: "pk-bucket-monogram-tory-burch",
    name: "Túi Bucket T Monogram Tory Burch",
    designer: "Tory Burch",
    price: 400000,
    deposit: 2000000,
    category: "Túi xách",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#f4efe7"],
  }),
  createProduct({
    id: "pk-trang-suc-bac-swaroski",
    name: "Set trang sức bạc Swaroski",
    designer: "Swaroski",
    price: 500000,
    deposit: 2000000,
    category: "Trang sức",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#d8d8d8"],
  }),
  createProduct({
    id: "pk-trang-suc-ngoc-trai",
    name: "Set trang sức ngọc trai",
    designer: "FASTWear",
    price: 200000,
    deposit: 800000,
    category: "Trang sức",
    gender: "Nữ",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#fff8f1"],
  }),
  createProduct({
    id: "pk-dong-ho-daniel-wellington",
    name: "Đồng hồ da Daniel Wellington",
    designer: "Daniel Wellington",
    price: 200000,
    deposit: 800000,
    category: "Đồng hồ",
    gender: "Nữ",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#ffffff", "#c5a059"],
  }),
  createProduct({
    id: "pk-giay-nam-john-lobb",
    name: "Giày nam John Lobb City II",
    designer: "John Lobb",
    price: 500000,
    deposit: 2000000,
    category: "Giày",
    gender: "Nam",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["8"],
    colors: ["#1A1A1A"],
  }),
  createProduct({
    id: "pk-giay-tay-nam-bitis",
    name: "Giày tây nam Biti's",
    designer: "Biti's",
    price: 120000,
    deposit: 500000,
    category: "Giày",
    gender: "Nam",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["M", "L"],
    colors: ["#1A1A1A", "#3a2a1a"],
  }),
  createProduct({
    id: "pk-dong-ho-nam-seiko",
    name: "Đồng hồ nam Seiko",
    designer: "Seiko",
    price: 200000,
    deposit: 800000,
    category: "Đồng hồ",
    gender: "Nam",
    occasion: ["Dạo phố", "Chụp ảnh"],
    sizes: ["37mm"],
    colors: ["#1A1A1A", "#345b86", "#ffffff"],
  }),
  createProduct({
    id: "pk-kep-caravat",
    name: "Kẹp caravat",
    designer: "FASTWear",
    price: 50000,
    deposit: 50000,
    category: "Phụ kiện nam",
    gender: "Nam",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#d8d8d8", "#c5a059", "#1A1A1A"],
  }),
  createProduct({
    id: "pk-khuy-mang-set-tron",
    name: "Khuy măng sét tròn",
    designer: "FASTWear",
    price: 50000,
    deposit: 50000,
    category: "Phụ kiện nam",
    gender: "Nam",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#d8d8d8", "#c5a059", "#1A1A1A", "#345b86"],
  }),
  createProduct({
    id: "pk-ghim-cai-ao",
    name: "Ghim cài áo",
    designer: "FASTWear",
    price: 50000,
    deposit: 50000,
    category: "Phụ kiện nam",
    gender: "Nam",
    occasion: ["Tiệc cưới", "Dạ hội", "Chụp ảnh"],
    sizes: ["Free"],
    colors: ["#d8d8d8", "#c5a059", "#1A1A1A", "#fff8f1"],
  }),
];

export const formatVND = (n: number) => new Intl.NumberFormat("vi-VN").format(n) + "₫";
