export type Product = {
  id: string;
  name: string;
  designer: string;
  price: number;
  deposit: number;
  category: string;
  gender: "Nữ" | "Nam" | "Unisex";
  occasion: string[];
  sizes: string[];
  colors: string[];
  available: boolean;
  rating: number;
  image: string;
  images?: string[];
};

const img = (q: string, i = 1) =>
  `https://images.unsplash.com/${q}?auto=format&fit=crop&w=900&q=80&v=${i}`;

export const products: Product[] = [
  {
    id: "1",
    name: "Đầm hoa mẫu đơn",
    designer: "DIOR",
    price: 350000,
    deposit: 1500000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Tiệc / Sự Kiện", "Cưới"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["#F6D7DF", "#FFF8F1"],
    available: true,
    rating: 4.9,
    image: "/media/product-peony-dress.webp",
    images: ["/media/product-peony-dress.webp"],
  },
  {
    id: "2",
    name: "Áo khoác drop họa tiết",
    designer: "DIOR",
    price: 480000,
    deposit: 2000000,
    category: "Áo khoác",
    gender: "Unisex",
    occasion: ["Công Sở", "Tiệc / Sự Kiện"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["#c9bea8", "#f4f1ea"],
    available: true,
    rating: 4.8,
    image: "/media/product-drop-jacket.webp",
    images: ["/media/product-drop-jacket.webp"],
  },
  {
    id: "3",
    name: "Nón bucket beige",
    designer: "DIOR",
    price: 420000,
    deposit: 1800000,
    category: "Phụ kiện",
    gender: "Unisex",
    occasion: ["Du Lịch", "Hàng Ngày"],
    sizes: ["Free"],
    colors: ["#d8ccb7", "#f4efe7"],
    available: true,
    rating: 5.0,
    image: "/media/product-bucket-beige.webp",
  },
  {
    id: "4",
    name: "Túi Bow hồng",
    designer: "DIOR",
    price: 180000,
    deposit: 800000,
    category: "Phụ kiện",
    gender: "Nữ",
    occasion: ["Hàng Ngày"],
    sizes: ["Free"],
    colors: ["#f1cbd6"],
    available: true,
    rating: 4.6,
    image: "/media/product-bow-bag-pink.webp",
  },
  {
    id: "5",
    name: "Đầm Maxi Bãi Biển",
    designer: "Reformation",
    price: 290000,
    deposit: 1200000,
    category: "Đi biển",
    gender: "Nữ",
    occasion: ["Du Lịch"],
    sizes: ["XS", "S", "M"],
    colors: ["#F2C4CE"],
    available: false,
    rating: 4.7,
    image: img("photo-1515886657613-9f3515b0c78f"),
  },
  {
    id: "6",
    name: "Blazer Công Sở Camel",
    designer: "YODY",
    price: 250000,
    deposit: 1000000,
    category: "Công sở",
    gender: "Nữ",
    occasion: ["Công Sở"],
    sizes: ["S", "M", "L"],
    colors: ["#c9a27a"],
    available: true,
    rating: 4.5,
    image: img("photo-1591047139829-d91aecb6caea"),
  },
  {
    id: "7",
    name: "Đầm Đen Tiệc Tối",
    designer: "SIMKHAI",
    price: 520000,
    deposit: 2200000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Tiệc / Sự Kiện"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["#1A1A1A"],
    available: true,
    rating: 4.9,
    image: img("photo-1566174053879-31528523f8ae"),
  },
  {
    id: "8",
    name: "Sơ Mi Nam Linen",
    designer: "LOCAL BRAND",
    price: 150000,
    deposit: 600000,
    category: "Áo",
    gender: "Nam",
    occasion: ["Hàng Ngày", "Du Lịch"],
    sizes: ["M", "L", "XL"],
    colors: ["#ffffff", "#cfe3e2"],
    available: true,
    rating: 4.4,
    image: img("photo-1602810318383-e386cc2a3ccf"),
  },
  {
    id: "9",
    name: "Quần Tây Slim",
    designer: "PEDRO",
    price: 180000,
    deposit: 700000,
    category: "Quần",
    gender: "Nam",
    occasion: ["Công Sở"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["#1A1A1A", "#3a3a3a"],
    available: true,
    rating: 4.5,
    image: img("photo-1473966968600-fa801b6f7f7f"),
  },
  {
    id: "10",
    name: "Đồng Hồ Da Cổ Điển",
    designer: "URBAN REVIVO",
    price: 120000,
    deposit: 1500000,
    category: "Phụ kiện",
    gender: "Nam",
    occasion: ["Công Sở", "Hàng Ngày"],
    sizes: ["Free"],
    colors: ["#3a2a1a"],
    available: true,
    rating: 4.8,
    image: img("photo-1524805444758-089113d48a6d"),
  },
  {
    id: "11",
    name: "Giày Cao Gót Đỏ",
    designer: "MISCHA",
    price: 200000,
    deposit: 900000,
    category: "Giày",
    gender: "Nữ",
    occasion: ["Tiệc / Sự Kiện", "Prom"],
    sizes: ["35", "36", "37", "38"],
    colors: ["#6B1A33"],
    available: true,
    rating: 4.7,
    image: img("photo-1543163521-1bf539c55dd2"),
  },
  {
    id: "12",
    name: "Đầm Prom Pastel",
    designer: "VERONICA BEARD",
    price: 460000,
    deposit: 1900000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Prom", "Sinh nhật"],
    sizes: ["XS", "S", "M"],
    colors: ["#F2C4CE", "#e7d4ff"],
    available: true,
    rating: 4.9,
    image: img("photo-1469334031218-e382a71b716b"),
  },
  {
    id: "13",
    name: "Đầm Satin Xanh Ngọc",
    designer: "FASTWEAR TEST",
    price: 390000,
    deposit: 1600000,
    category: "Đầm Dự Tiệc",
    gender: "Nữ",
    occasion: ["Tiệc / Sự Kiện", "Cưới", "Prom"],
    sizes: ["S", "M", "L"],
    colors: ["#043927", "#D4AF37"],
    available: true,
    rating: 4.8,
    image: img("photo-1595777457583-95e059d581b8", 13),
    images: [
      img("photo-1595777457583-95e059d581b8", 13),
      img("photo-1566174053879-31528523f8ae", 13),
    ],
  },
];

export const formatVND = (n: number) => new Intl.NumberFormat("vi-VN").format(n) + "₫";
